### ISSUE TITLE
Upload images in the background, allow multiple

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet-mobile#107]

**Comment by dracos** [comment]
Server side work is present for this to happen now.

**Comment by abimysoc** [comment]
User support email asking about multiple photo upload today.

**Comment by abimysoc** [comment]
User points out that the lack of ability to upload >1 photo on mobile "contradicts the advice on the site to upload 2 pictures".

**Comment by abimysoc** [comment]
User feedback:

> When filing a report I would like to be able to upload several images, one of the flytipping item close up and another of the general area. Please can you add multiple pictures upload to the app.

**Comment by dracos** [comment]
PR at https://github.com/mysociety/fixmystreet-mobile/pull/260 for multiple photos.
