### ISSUE TITLE
workflow when invalid password

### ISSUE THREAD

**Issue by MartinDigon** [mysociety/fixmystreet-mobile#119]
Device: Samsung Galaxy S4 (model GT-I9505) running Android 4.2.2.

The following workflow needs rethinking:
 1.- Create report.
 2.- Provide wrong password when prompted.
 3.- Report appears to upload (takes a while with a large image).
 4.- Upload fails with "There was a problem with your email/password combination.":
![2013-08-22 21 06 37](https://f.cloud.github.com/assets/205956/1058587/37d88066-118b-11e3-87d2-515e9288a254.png)

It should validate the password before spending the time trying to upload the report.

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper.
