### ISSUE TITLE
photo orientation

### ISSUE THREAD

**Issue by MartinDigon** [mysociety/fixmystreet-mobile#122]
Device: Samsung Galaxy S4 (model GT-I9505) running Android 4.2.2.

When adding a photo to a report (either by taking the photo in-app or by selecting an existing photo from the phone), the photo is previewed in landscape orientation even if it was taken in portrait orientation.
![2013-09-03 08 48 21](https://f.cloud.github.com/assets/205956/1071281/b46fe9ae-1472-11e3-86ac-363ee51c99f9.png)

Probably related to the way in which the S4 stores EXIF orientation data in the JPEG: for portrait photos it should be storing the orientation as right-top (0x06), but it seems to store it in such a way that it confuses some apps and image viewers (e.g. the Instagram app also gets the orientation wrong, so you're in good company).

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper.
