### ISSUE TITLE
User bug report - invalid report

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#156]
"When I try to add a report to fix my street app it keeps saying invalid report this information required ( it doesn't say what information this is). it also says my email/password combination is incorrect so I change d my password successfully and it still says invalid report this information required . This only happens on the app.

"I have checked and there are no updates so I am using the most up to date version .i am running iOS 7.0.2"

**Comment by davea** [comment]
This seems to be occurring again. Logged-in users are seeing the 'this information is required' error when trying to submit reports to Bromley in certain circumstances.

So far this is the most reliable way to reproduce the bug that I've found:

 1. Delete the app entirely from your device
 1. Set your user record's `title` field to NULL in the FMS database, if not already
 1. Reinstall the app, and log in to your account
 1. Make a report within Bromley (use 'App store test' for title so it doesn't actually get sent to Bromley)
 1. Select a title on the "Your details" screen:
  ![img_da6eeafa953e-1](https://user-images.githubusercontent.com/4776/35401853-9e281032-01f2-11e8-8b91-407b4864d846.jpeg)
 1. Submit the report and observe the error:
  ![img_934dda8dd20d-1](https://user-images.githubusercontent.com/4776/35401884-b6d80740-01f2-11e8-97f9-57bfc1dfffed.jpeg)

On occasion if you hit 'back' at this point the problem title has changed from 'App Store test' to whatever title you picked from the dropdown...

There is a workaround:

 1. Sign out of your account in the app
 1. Make a report to Bromley, using the 'I've already got [a password] - login' button
 1. Confirm the report in the email that arrives
 1. Go back to the app and sign in again, and the title field will correctly be populated for future reports, bypassing the bug.

**Comment by dracos** [comment]
SubmitNameView (confirm by email/set a password flow) and SubmitPasswordView (already got a password flow) both handle `titles_list` in their `validate()`/`beforeSubmit()`, but SubmitConfirmView (already logged in flow) appears to have nothing to set the title on the user.

**Comment by abimysoc** [comment]
Another user has run up against what looks like this bug again; they said "I keep getting a error reporting to Bromley. It works on the website but not on the app." and provided the attached screenshot (which I've anonymised).

![image1](https://user-images.githubusercontent.com/560001/36377872-8cbd3642-1570-11e8-8ecb-a4c182535961.png)

**Comment by abimysoc** [comment]
Another user has emailed about the "invalid report" error message, and they are NOT in Bromley - this was a report in Derbyshire. Hmm.

![image1](https://user-images.githubusercontent.com/560001/36737737-a8ca26f6-1bd3-11e8-86dd-4829014f82ee.PNG)

**Comment by MyfanwyNixon** [comment]
Yes, I am trying to make a report in Brighton and got this error.
I chose both 'send me a confirmation email' and then 'I'll log in' and both times got an invalid report message. Presumably the report is then just lost - just looked in admin and it's not there as unconfirmed or anything.

**Comment by abimysoc** [comment]
Other recent correspondence on the issue (since start of March):

Moto G, Android 5.1, vicinity of SL6 0EU. The Bromley workaround that @davea details above worked in this case.

iOS10 on iPhone SE, London N5 and Stroud areas. Workaround suggested, no reply to confirm whether it was tried/worked.

Another person replied to a "please give us some more info to help debug this" email saying that it was now fine and "I didn’t know I had to be logged in to the app for it to work", which might suggest they inadvertently worked around the bug.

Two people this week have emailed about it, we wait to see if they respond with any useful diagnostic info.

**Comment by MyfanwyNixon** [comment]
So it's hard to go and try it again myself without a genuine problem to report but I definitely remember doing the following:

- Open app, am geolocated
- Pan the map slightly to get the right location, click 'reposition report here'
- Add a photo, uploaded from my photo roll (side note, in trying to replicate this I am now getting a different issue: uploading the photo and clicking 'next' does nothing)
- Fill in title, category and details of problem (similar to https://www.fixmystreet.com/report/1277988 which is the report I made on my desktop after the app didn't work for me)
- I think at this stage I went for 'I've already got a password - log in' and got the 'invalid report' error; tried again with 'I don't want to set a password', got the error again, gave up and reported on my PC.

**Comment by davea** [comment]
Boom, got it. Thanks, that's been really helpful in tracking it down.

Looks like when the POST to `/report/new/mobile` returns an error for the `password_register` field (e.g. password not long enough, too common, etc) the app doesn't do the right thing. I'll sort that out.

**Comment by MyfanwyNixon** [comment]
I'm amazed that was helpful, but I'm glad it was!
