### ISSUE TITLE
User feedback: alert boxes hide map

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#160]
"Great app but could I suggest that you don't keep the text box re location services up all the time and make the yellow new report here text box smaller and down a bit. This would give a lot more visible map display area."

![image](https://f.cloud.github.com/assets/944656/2049149/d26afa12-8a5a-11e3-8365-5c4f5f935808.png)

**Comment by dracos** [comment]
Looks to have been done in that commit.
