### ISSUE TITLE
User feedback: Android app

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#161]
1. When using Swype keyboard to enter text, no space is entered between words automatically (titles, descriptions).
2. Android back button does not work to exit the app.
3. Android menu key does nothing, when it could do something useful.

**Comment by Gemmamysoc** [comment]
User feedback:

"App on android not working as many pages will not allow you to go
back to previous page!! Also no way to close app! Also default
setting on response should be annonomus hard to remember to untick
every time"

**Comment by dracos** [comment]
Closing as old.
