### ISSUE TITLE
Add 'Hide pins' option to app

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet-mobile#175]
A few app users have noted that fixed problems are clogging up the map view on the app, so they're finding it difficult to report new problems. They have asked if there is a way to hide the pins when they are making new reports. There currently isn't an option to 'Hide pins' on the iPhone app.

**Comment by zarino** [comment]
FWIW, commit https://github.com/mysociety/fixmystreet/commit/5b756abb1aa66f264564941d1df643afff0bac28 added "mini" pins to the *web* version of FixMyStreet when you zoom out, to combat this same problem (pins too big and too close, can’t click map).

Doesn't help those using the app though :-/

**Comment by MyfanwyNixon** [comment]
https://twitter.com/brucevdkooij/status/756451228041748480

> <3 your app. But, why does the Reporting map show Fixed reports? It's getting a bit busy round here :-)

**Comment by abimysoc** [comment]
+ 1 from a user

> How do i Remove pins from mobile phone fix my street app. no remove button on map to remove pins

**Comment by abimysoc** [comment]
> Anyway of filtering the map? There are so many reports (yellow markers) that it is impossible to see on a mobile device if the problem has been reported. Would be great to apply a filter for the last 4 weeks for example.

**Comment by MyfanwyNixon** [comment]
Via Facebook:
>For your app - please can you set t so that you can toggle completed reports off? I can't see where to pin new reports as old pins are covering where I am.

**Comment by abimysoc** [comment]
Support email:
>It's impossible to locate streets as I can't see them beneath the pins!

**Comment by abimysoc** [comment]
Suggestion from a user of hiding only certain types of pins:

> When I want to report a problem on the app it opens up with lots of reports or pins. When I look at them most seen to be closed. Would it not be better to only display Open calls not All Calls?

**Comment by MyfanwyNixon** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/fixmystreet?ref_src=twsrc%5Etfw">@fixmystreet</a> is next to useless, in this location, as there are multiple pins in there, some dating back to 2009! at the very least, it needs a date filter</p>&mdash; Colin (@theabingdontaxi) <a href="https://twitter.com/theabingdontaxi/status/977266241210634240?ref_src=twsrc%5Etfw">March 23, 2018</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">thank you, mate, I’m not sure it works on the app, though, or have I missed it? <a href="https://t.co/mvHuLk7oT5">pic.twitter.com/mvHuLk7oT5</a></p>&mdash; Colin (@theabingdontaxi) <a href="https://twitter.com/theabingdontaxi/status/978251664527450112?ref_src=twsrc%5Etfw">March 26, 2018</a></blockquote>

**Comment by abimysoc** [comment]
> Buttons to filter reports shown on map to most recent or over last year etc. (As the map has become too crowded!)
