### ISSUE TITLE
Add more explicit way to save current report

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet-mobile#182]
If you're out and about and just wanting to mark problems for later completion then there's currently no way to save the existing report as a draft and start a new one unless you quit the app and start again which isn't very obvious. There should be a save draft and start again mechanism.

**Comment by Gemmamysoc** [comment]
+1 from user: 

"iPhone App Feedback: If it cannot recognise the location it cannot move forward. It should allow us to complete all the details while in situ, and save the report as a draft for the location to be filled in at leisure.

At present it simply falls at that hurdle, and chuckles at the user."
