### ISSUE TITLE
location_check_failed GPS error

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#189]
Hello, everyone!

I'm having a problem related to GPS, where the "location_check_failed" error is raised.

I've only tried the application on Android. I got the error in the emulator, but my Galaxy Tab 10.1 produces the problem (with or without Location services being on), and a user with a Samsung Galaxy S5 have also reported the problem (I don't know what his Location services setting was).

I could reproduce the issues with the following steps:

1. Check out fixmystreet-mobile's master branch
2. Copy src/js/config.js-example to src/js/config.js
3. Set LANGUAGE to 'en', APP_NAME to 'FixMyStreet', and FMS_URL to 'https://www.fixmystreet.com'
4. Run the application in the Android emulator with location services disabled
5. Type "London" in the text field
6. Click "New Report Here" and "Confirm Location"

Here, I get an error saying "There was a problem checking we cover this location. Please try again later.". I would expect the app to allow me to create the problem and submit it to the server without GPS connectivity, based on the position that I have selected on the map.

Might be related to #176.

Thanks!

**Comment by struan** [comment]
Ah, I should make sure that's documented. And also fix the double slash issue.

**Comment by jonkri** [comment]
I guess this issue can be closed, so I'm closing it. :)
