### ISSUE TITLE
Parse error on comma in GPS coordinates

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#190]
On FixaMinGata, our post code lookups looks like this (with commas before the decimals):

http://beta.fixamingata.se/ajax/lookup_location?term=41516

This causes the Ajax request in fixmystreet-mobile (on line 16 in locate.js) to fail due to a parse error.

We should either document that postcode lookups need to be using dots instead of commas, or modify the code to support comma separators.

**Comment by jonkri** [comment]
I'm confused - when I'm trying this now, it seems to work, even with commas. I'll re-open this issue if I manage to reproduce it again.

**Comment by dracos** [comment]
I don't think we want non-JS-correct floating point numbers (in JavaScript, they should always be with a decimal point), so I think this probably is an actual issue (with the server side, so hopefully easily fixable) - I'm not entirely sure why it seems to work for you, though!

**Comment by jonkri** [comment]
OK, I don't know why it was working, or why I thought it was working, but it's not. :>

Should I open an issue on mysociety/fixmystreet?

**Comment by dracos** [comment]
This should hopefully now be fixed on master if you'd like to give it a go and let us know.

**Comment by jonkri** [comment]
Thanks!

I noticed that the return value went from:

    {"longitude":12,05197,"latitude":57,752934}

To:

    {"longitude":"12.05197","latitude":"57.752934"}

Note that not only the comma changed to a period, but that the values became string values.

It seems to work, though. :)

**Comment by dracos** [comment]
Yes, it seems easiest to handle if they're strings, and it should work fine, goodo.
