### ISSUE TITLE
Improve 'Show your name publicly' page on app

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet-mobile#194]
User using android app on Samsung Galaxy smartphone. 

Their feedback:

"The screen that says do you want to show your name. It isn't clear
on my s5 phone if you are checking or un checking the option.can you
make it clearer.at present the back ground is either transparent or
if you push it it fills in....what is what"
![screenshot_2015-01-30-17-31-21](https://cloud.githubusercontent.com/assets/6806067/6002048/bd91a1f0-aae7-11e4-923e-8f712e493102.png)

**Comment by Gemmamysoc** [comment]
User feedback: "Box for making sure report is anonamous unclear and broken on mobile
app. Make option larger and clearer at start of report."

**Comment by Gemmamysoc** [comment]
User feedback:

"When i use my laptop to make a report it is clear for me to put a
report in anonymously, but on my mobile i can't figure it out, is
there a way to remain anonymous permanently rather than having to
choose every time. Also had to do this on laptop as mobile site
won't accept my email address, says "please enter a valid email
address" (there is no space at the end) have also tried another
email in case that was the one i registered with"

**Comment by dracos** [comment]
Think this has been fixed by #219
