### ISSUE TITLE
The possibility of (visiting reported problems and) marking problems as solved

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#199]
A user might want to use the app to mark a problem as solved. As it is now, the user has to go through the web application. A flow for this use case could be logging in to the account, selecting the problem from a list of submitted problems, and pressing a "Mark as solved" button, or something like that.

**Comment by MyfanwyNixon** [comment]
Similar request from a user via Twitter:

> love the iOS app! Made repair reporting so much easier. Any chance of enabling to view report history within the app?

https://twitter.com/gerwyn/status/684480011055820800

**Comment by poVoq** [comment]
Any update on this?

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper (which can do this)
