### ISSUE TITLE
Help "compiling

### ISSUE THREAD

**Issue by otmezger** [mysociety/fixmystreet-mobile#200]
Hi, 

i'm new to phonegap and I'm trying to get the fixmystreet-mobile code running. I already have a server with fixmystreet running. 

this is what I did:

    git clone git@github.com:mysociety/fixmystreet-mobile.git
    cd fixmystreet-mobile
    
Then I edited the config.js file, and added the ip of my FMS server. I edited only this lines:

    APP_NAME: 'My Own FMS app',
    FMS_URL: '192.168.1.204',

Then I went to the project directory and entered

    phonegap run ios

and got 

    [phonegap] executing 'cordova run ios'...
    Current working directory is not a Cordova-based project.

sorry if this is a stupid question, but I just can't find the way of running it. Thanks for your help

**Comment by stevenday** [comment]
Hi,

Sorry for the trouble. The master branch of this repo is currently using quite old versions of phonegap/cordova (2.9 and 2.5 I think). It's structured in a different way to newer versions, in that there are two separate Cordova projects inside the iPhone and Android directories respectively. 

You might find it easier to base your work off the phonegap-3 branch, which has been updated to a much newer version, and follows the newer conventions. It also has some more thorough instructions for building the app in the REAMDE: https://github.com/mysociety/fixmystreet-mobile/tree/phonegap-3

Hope that helps.

**Comment by otmezger** [comment]
Hi @stevenday, thanks for the help. It worked perfectly, now I can run the cordoba project normally.
