### ISSUE TITLE
To have cobranded pins

### ISSUE THREAD

**Issue by lfalvarez** [mysociety/fixmystreet-mobile#205]
It'd be awesome if you could have a different set of pins in your app than the original ones, and you could add them to somewhere like `www/cobrands/<your-cobrand>/images/` (could also be `/pins`).

I think that it can be achieved by adding the `CONFIG.cobrand` thing in https://github.com/mysociety/fixmystreet-mobile/blob/phonegap-3/www/js/map-OpenLayers.js#L79.

Thanks a lot for the cobranding thing it makes everything way easier :smile:

**Comment by dracos** [comment]
This app no longer in use, moved to PWA (which can then do this)
