### ISSUE TITLE
[MV] Update FAQ attribution

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#207]
From in partnership with the Maldives Police Service and Greater Male' Waste Authority
to in partnership with the government

**Comment by davewhiteland** [comment]
See https://github.com/mysociety/fixmystreet-international/issues/29 (duplicate)

**Comment by davewhiteland** [comment]
I can't find any attribution to cooperation with the police in the MakeMyIsland branded app, so I believe this only applies to the website -- closing the issue on mobile.
