### ISSUE TITLE
Corrupt app state due to an invalid SSL certificate?

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#212]
We recently had a problem with an expired SSL certificate on FixaMinGata. During the time when there was an invalid certificate on fixamingata.se, a user installed the FixaMinGata app on an iPhone 5S and tried to log in by pressing the top-right button. What happened was that nothing happened, except that the button turned partially green.

![img_2352](https://cloud.githubusercontent.com/assets/777056/12743818/aaa50bea-c990-11e5-9591-3fbec7090291.PNG)

After the certificate problem was resolved, the app still had the same problem. Rebooting the phone (and restarting the app) did not help - however, uninstalling and reinstalling the app from Apple's app store did.

Please note that this defect seem persistent in nature, in that it seems capable of essentially making an app installation unusable.

**Comment by dracos** [comment]
I'm not sure what this could have been, nor can I think about what to do, I don't think we do anything in this area ourselves in the codebase, it's all in the underlying framework. Perhaps the upgrade will have done something here quite possibly, but even if not, I don't think there's anything we can do.
