### ISSUE TITLE
App requiring permanent access to GPS

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#213]
https://twitter.com/ontwoplanks/status/697007929002741760

> Why does @fixmystreet require permanent access to GPS and why does it use a geofence to detect I'm at home? #privacy 

![fms home](https://cloud.githubusercontent.com/assets/944656/12914404/135ba0be-cf1c-11e5-811a-5d469f15e1c5.png)

> There should be a third option of gps permission only when in app, and the geofence (permanent tracking) is just weird.

**Comment by dracos** [comment]
There is nothing in the codebase I can see that does anything about geofences.
Nor can I see anywhere we ask for permanent GPS access. I'm just trying to track these down.

**Comment by dracos** [comment]
<img src="https://cloud.githubusercontent.com/assets/154364/14825713/e07509d0-0bd2-11e6-8ace-82a90e1a637c.png" width="50%" align="right">
This is what I have in the emulator now, so let's hope the new version fixes this. I certainly don't know how a geofence would have been implemented, there's no code for it, and we haven't had anyone else mention this, so I'm confused on that.

**Comment by abimysoc** [comment]
> Could the app have an option for location used when the app is in
use? Having location settings as always drains the battery.

**Comment by dracos** [comment]
Believe this is fixed in new release, reopen if not.
