### ISSUE TITLE
If you visit a web page (individual report, unresponsive help), Back doesn't work

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#218]
It's impossible to get back to the app once you've done this, you have to home/exit otherwise and reload the app.

**Comment by dracos** [comment]
Fixed in #219.

**Comment by jonkri** [comment]
Nice that this is now fixed. By the way, what does "unresponsive help" mean in the title?

**Comment by dracos** [comment]
In the UK we have a bit of custom code to display a message if a council has refused to accept messages.
