### ISSUE TITLE
Text on long reports is hidden behind keyboard on iOS

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet-mobile#222]
If you are typing a long report then the screen doesn't scroll which means that the text is eventually obscured by the keyboard:

![image-1](https://cloud.githubusercontent.com/assets/5310/14892862/c3b22178-0d64-11e6-9f43-573aa7aa00d3.jpg)

I've checked the existing version and it doesn't exhibit this behaviour:

![img_4915](https://cloud.githubusercontent.com/assets/5310/14892946/38f33ab2-0d65-11e6-9603-3f6612fbf3fe.PNG)

**Comment by abimysoc** [comment]
User email, iPhone 6S:

> When typing out my report I can only write so many lines before the text disappears behind the keyboard. I try to keep the word count low but not always possible.
