### ISSUE TITLE
Change category dropdown item color

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#232]
A user felt that it was inconsistent that the placeholder text for the title and description when creating a problem report is grey, while the "select category" text is black. Do you think it would make sense to change the "placeholder" text for the category dropdown menu to grey as well?

![4](https://cloud.githubusercontent.com/assets/777056/18150250/b05868d8-6fe5-11e6-8513-237de803d123.png)

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper.
