### ISSUE TITLE
Update needed to Android location permissions

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet-mobile#235]
Google have changed their config file to require apps that use the ACCESS_FINE_LOCATION permission to explicitly declare that they need access to the GPS hardware: https://forums.adobe.com/thread/2211532

According to that page, we just need to add 

``` XML
<platform name="android">
    <config-file target="AndroidManifest.xml" parent="/*">
            <uses-feature android:name="android.hardware.location.gps" />
    <config-file>
</platform>
```

to our config.xml and then release it.

**Comment by stevenday** [comment]
We have until the 15th of October to make this change, and it affects all of the apps which use this repo.

**Comment by dracos** [comment]
It's only if you target version 21 or higher (5+), and we currently target 16 (4.1+), if I've read it right.

It's a bit odd. I don't see any problem with the app being installed on a device that lacks GPS hardware, you could still use wi-fi/cell-id based location. The email from Google said: "Also, if you’re using the fused location provider and wish to receive the most accurate location samples from GPS (i.e. with PRIORITY_HIGH_ACCURACY), you must include the "android.hardware.location.gps" feature in your app’s manifest to ensure that Google Play only distributes your app to devices with GPS sensors." – so it's no longer possible to get the highest accuracy whatever device you happen to be on? Seems stupid to me.

**Comment by stevenday** [comment]
Our min SDK version is 16 but we have a target version of 23, I assumed this is what they meant by targetting. I presumed that they sent the emails based on what we have configured in our AndroidManifest.xml for each app but I might be wrong

**Comment by stevenday** [comment]
(it is an odd change though, you're right)

**Comment by dracos** [comment]
Ah, right; can we target a lower version? :)

**Comment by stevenday** [comment]
Apparently the device [might start enabling compatibility features](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#target) if sees a target version lower than the current version of android it's running. I can't see any obvious ones in https://developer.android.com/reference/android/os/Build.VERSION_CODES.html that would cause us problems (the most recent version to mention them is 14 and we already have a minimum of 16 but I guess we wouldn't know if something changed in a future release.

Since we'd need to change the file and re-release to change that anyway, it doesn't seem worth the risk?

**Comment by stevenday** [comment]
Turns out this is easier to fix by just upgrading the geolocation plugin for phonegap. I've done that for FMS and released the app. Will do the same for the following now:
- Zurich
- MakeMyIsland

**Comment by stevenday** [comment]
I've done zurich, awaiting davea to find the keys for MakeMyIsland so we can release that too

**Comment by davea** [comment]
I've pushed the MMI key. Sorry about that!

**Comment by dracos** [comment]
Assumed done.
