### ISSUE TITLE
[CuidoMiCiudad] Final translations

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet-mobile#238]
There are a couple of places that still need to be translated into Spanish:

 - [x] The [welcome screen](https://github.com/mysociety/fixmystreet-mobile/blob/cuidomiciudad/www/templates/es/initial_help.html):
![simulator screen shot 9 mar 2017 12 30 20](https://cloud.githubusercontent.com/assets/4776/23750292/2d0b3572-04c4-11e7-80bf-0cc051f2758d.png)

 - [x] The [FAQ/help text](https://github.com/mysociety/fixmystreet-mobile/blob/cuidomiciudad/www/templates/es/help.html) (we can likely reuse the text from the main CMC site for this):
![simulator screen shot 9 mar 2017 12 28 59](https://cloud.githubusercontent.com/assets/4776/23750272/0c163222-04c4-11e7-99e4-6f92241d830e.png)

**Comment by JenMysoc** [comment]
So the FAQ is loaded up on the fms-international repo. Hopefully that can easily port over to the app (same with the privacy stuff)
