### ISSUE TITLE
Cordova not running 

### ISSUE THREAD

**Issue by filmontewelde** [mysociety/fixmystreet-mobile#242]
Hi, 

I'm currently trying to use your project "fixmystreet-mobile-master", but I can not use cordova with it. 
When I do "cordova prepare" in the projet it say "Error : Current working directory is not Cordova-based projetc.", have you a solution for that ?

Thank you

**Comment by davea** [comment]
Hi there,

This is likely caused by `config.xml` not being found. You need to copy `config.xml-example` to `config.xml`, and make the appropriate changes to link it to an instance of FixMyStreet before running `cordova prepare` again.

Hope this helps!

**Comment by filmontewelde** [comment]
Yes thank you.

But now when I do "cordova emulate android" it say "Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable." and even when I add the path in ANDROID_HOME it's just continu to say the same thing.

Do you know what do I miss ?

Thanks again
