### ISSUE TITLE
[CuidoMiCiudad] Change App FAQ 

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-mobile#243]
Change the FAQ on the app to just show the following for the website:

![screen shot 2017-03-28 at 15 39 03](https://cloud.githubusercontent.com/assets/4170351/24411121/f4f28c5e-13cc-11e7-9e3d-fe16710585ff.png)

**Comment by davea** [comment]
Done. Released for Android and pending review for iOS (will be automatically released after passing  app review).
