### ISSUE TITLE
Sometimes the top right button isn't touchable

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#244]
I'm on the photo screen, and "Skip" if I don't select a photo or "Next" if I do, does nothing if touched. I have to click Back then confirm location (at least it remembers the photo) and then it works fine.

**Comment by davea** [comment]
Steps to reproduce:

1. Tap "New Report Here" on the map screen
1. Tap "Confirm location"
1. Tap "Skip" on photo screen
1. Select a category
1. Tap "Back", "Back", "Cancel" to return to the map
1. Tap "New Report Here" on the map screen
1. Tap "Confirm location"
1. Tap "skip" on photo screen - at this poin the bug occurs and you can't continue.
