### ISSUE TITLE
Location deviates from original position of map pin

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#247]
A user of FixaMinGata's iOS app has reported that the map pin ended up around 30 meters from where she (manually) positioned it using the app.

![fmg_ios_problem_0](https://user-images.githubusercontent.com/777056/27447925-1c8cad0e-5783-11e7-82e5-9c770072bbd6.png)

I tried to reproduce the problem using an emulator, but couldn't.

![fmg_ios_problem_1](https://user-images.githubusercontent.com/777056/27447943-34b85ed2-5783-11e7-8f27-2e57252eabf4.png)

![fmg_ios_problem_2](https://user-images.githubusercontent.com/777056/27447945-36ca3db2-5783-11e7-93d8-131f7844ec3b.png)

The user has created several reports using the app before, but has never had any problems. She says that she positioned the map pin in "exactly the right place", and that the pin was "moved significantly".

Does anyone have any ideas as to what can be the cause of this?

The user was using an iPhone 5s with iOS 10.3.2.

The admin interface says "used map".

The (incorrect) coordinate values of the report are 55.479476 and 13.513715.

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper.
