### ISSUE TITLE
User bug report: button styling

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#255]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/fixmystreet?ref_src=twsrc%5Etfw">@fixmystreet</a> This button&#39;s styling has been broken for a while. <a href="https://t.co/VNOwSJ9jmN">pic.twitter.com/VNOwSJ9jmN</a></p>&mdash; Jez McKean (@jezmck) <a href="https://twitter.com/jezmck/status/949768041008713728?ref_src=twsrc%5Etfw">January 6, 2018</a></blockquote>

![ds5a_djx0aadvuv](https://user-images.githubusercontent.com/944656/34664367-6989e1f4-f453-11e7-8f57-782afdcf25e7.jpg)

**Comment by dracos** [comment]
That's the website on a phone, not the app.

**Comment by dracos** [comment]
And the styling isn't perfect, but it looks usable to me, you can tell Yes is selected and you can tap No to select that? :) (I'm assuming they have an old browser, can't really tell more without them saying what browser they're using.)

**Comment by MyfanwyNixon** [comment]
>That's the website on a phone, not the app.

Oh, ok.

**Comment by jezmck** [comment]
Indeed, this is on the website - is there somewhere official to report it?

**Comment by dracos** [comment]
No need, I've just pushed and deployed a fix – https://github.com/mysociety/fixmystreet/commit/32be970f9519cda5ba3670e97ee6f243d159a54f – thanks for letting us know :)
