### ISSUE TITLE
Intermittent request for user to log in

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#256]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/fixmystreet?ref_src=twsrc%5Etfw">@fixmystreet</a> When I use your app on my Android phone, sometimes it asks me to log in and sometimes it doesn&#39;t, and sometimes after it&#39;s accepted the report it sends me an email asking me to confirm it. Why is this?</p>&mdash; Mike George (@ourMikeGeorge) <a href="https://twitter.com/ourMikeGeorge/status/951108661212057600?ref_src=twsrc%5Etfw">January 10, 2018</a></blockquote>

**Comment by abimysoc** [comment]
There have also been three or four recent complaints about this by email. Users who have entered their details in the 'Account' section of the app are (justifiably) annoyed that it isn't remembering their details and forcing them to go through the confirmation email step each time.

**Comment by abimysoc** [comment]
Where people have responded on the question of device/OS:

Android 6.0.1 Samsung S5 mini

Samsung S5 Mini (SM-G800F) rooted Marshmallow 6.0.1

Another mentioned Android but wasn't more specific than that.

**Comment by abimysoc** [comment]
Oh, and me :-/ On a Samsung Galaxy S8 Android 7.0, with app version 2.0.10. Although I had previously entered my details under 'Account' I found myself facing this:

![2018-01-23 09 24 04](https://user-images.githubusercontent.com/560001/35268015-ed109c66-001f-11e8-9b60-c9cf21702b24.png)

and when I went to look in the 'Account' section, my email address and password were not saved and needed to be re-entered. The email address is definitely being remembered somewhere though as it's the bit I've blurred out of that screenshot.

**Comment by dracos** [comment]
Think this might be the recent cookie changes.

**Comment by dracos** [comment]
This does appear to have been the case, have rolled back samesite=lax cookies for now until solution can be found.

**Comment by jonkri** [comment]
@dracos: In what version was the cookie change applied? Thank you!

**Comment by dracos** [comment]
It was never in a released version - it was added in https://github.com/mysociety/fixmystreet/commit/a9932722b4cf2103d35f8f4c23ad2918aad0a96c and removed in https://github.com/mysociety/fixmystreet/commit/6e415f3c6d9355312b9fb84e4ecdb68f96cff618
So actually, this issue is closed.
