### ISSUE TITLE
"Unresponsive" body message doesn’t display at all

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet-mobile#266]
From reading #245, it sounds like there used to be an equivalent in the app to this “Unresponsive body” message on the website:

![important-message](https://user-images.githubusercontent.com/739624/41242394-4bbef976-6d97-11e8-9ae6-fd8ec71e8f0e.png)

However, I can’t seem to trigger such a warning, now, using the iOS app. I _think_ the warning used to be displayed between the report details step and the login details step.

**Comment by dracos** [comment]
If this isn't fixable serve-side, and/or fixing #245 at same time would be good!
