### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by openmotion** [mysociety/fixmystreet-mobile#274]
hello
i installed node , android sdk 
but when i execute :  cordova prepare --verbose
in the folder : /Users/xxxx/Projects/fixmystreet-mobile
i have this response
Current working directory is not a Cordova-based project.

node --version && npm --version 
v12.4.0
6.9.0

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper.
