### ISSUE TITLE
Unable to progress past photo adding step on iPhone 11 / iOS 13

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet-mobile#281]
1. Open FMS app.
2. New report at current location.
3. Select a photo to attach.
4. Photo is shown on screen, but there’s no way to progress:

   ![IMG_8810](https://user-images.githubusercontent.com/739624/65706490-7c762a80-e082-11e9-8f80-34de4e1072e8.jpg)

5. Force quit the app.
6. Reopen the app.
7. Click on "Drafts" toolbar item, and continue report.
8. Reconfirm location.
9. Notice that now, on the photo screen, the toolbar is visible, and you can proceed as normal:

   ![IMG_8811](https://user-images.githubusercontent.com/739624/65706559-a2033400-e082-11e9-82c5-d964db374ac9.jpg)

**Comment by davea** [comment]
Seems to be caused by this: https://github.com/apache/cordova-plugin-camera/issues/507

Investigating workarounds.
