### ISSUE TITLE
Configuration parameter for always showing the initial help

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet-mobile#284]
We would like to show the initial help at every start of the app (with some brief reminders in it about things like avoiding personal information in problem descriptions).

Some motivation why we'd like to do this:

_Sometimes users who find out about the mobile app first and are unaware of the website are surprised (or angry) when they find out the reports are published online._ 

_The website has helpful tips (like "don't include personal information in the description") that you see when creating a report, but it's hard to fit that into the UI for the app I think._

I'll create a PR shortly with a suggested implementation.

**Comment by joesiltberg** [comment]
See PR #285

By the way, I was a bit confused for a while by some "android2" specific code when I looked at this. I suppose we don't need that anymore? Would you like me to get rid of it?

**Comment by davea** [comment]
Thanks for the PR, merged in c9042bf54382713a00a3eb2ce0c5b7527ce4964e.

Feel free to submit another PR removing the `android2` code. As you say, it's not needed any more.

**Comment by joesiltberg** [comment]
@davea : made a separate PR for the android2 code, see #290
