### ISSUE TITLE
Adding multiple photos crashes on iOS 14

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet-mobile#296]
The app crashes and returns the user to the home screen on iOS when attempting to add more than one photo.

Steps to reproduce:

 1. Start a new report and tap the "add an existing photo" button
 1. Select a photo, or tap "cancel" to close the popover
 1. Tap the "add an existing photo" button again
 1. Observe that app disappears and you go back to the iOS homescreen

Strangely if you tap the "Take a new photo" button before pressing the "add an existing photo" button for the second time the crash is avoided.

**Comment by LouiseMySociety** [comment]
A better option than it not working would be just to allow one photo.
