### ISSUE TITLE
iOS app forcing users to log in each time [4hrs]

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet-mobile#300]
Had a couple of user support requests recently about the iOS app forcing people to log in every time they want to make a report.

From 3rd May 2022

> I also recently noticed that the iOS phone app keeps forcing me to login each time I make a report using it rather than holding my login details from the previous session which it used to do. Is there something that changed in the way the app functions to cause this? I would prefer that I don't have to keep logging into the app on my phone.

From 22nd May 2022

> Every time I used the iOS app I need to login again - it didn’t used to work like this - something broke in the last month or two. Are you aware of this?

**Work required:**
- [ ] Investigate what the issue is

**Comment by dracos** [comment]
More, 7th June: " Hi. The App (iOS) requires me to login (enter my password) every time i want to make a report and often asks me to respond to a confirm email. Until recently it left me logged in all of the time, which is my preference. "
10th June: " This app has stopped working properly. I’m unable to log into my account. The screen doesn’t load properly and renders fuzzy. I’m unable to log a case on the app now. iPhone 13ProMax ios15.5. I have tried uninstalling and reinstalling the app. "
@davea Any ideas?

**Comment by sallybracegirdle** [comment]
More from September 22:

> I’m massively unimpressed with the [@fixmystreet](https://twitter.com/fixmystreet) app. It takes ages to find your location. Sometimes does not offer littering as a category and I have to log in every time I report something [@hackneycouncil]

> Each time I open the app on my iphone I have to enter my username and password. Surely it can be stored for ease of use?

**Comment by davea** [comment]
Submitted to App Store review.
