### ISSUE TITLE
[iOS] Unable to submit report. Asking for name when already entered.

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet-mobile#302]
From user support inbox:
> Can’t submit a report, app is asking me to enter name, although name is already entered, message is :
Invalid report
Please enter your name

Screen shot

![enter name bug ios](https://user-images.githubusercontent.com/9289297/217820176-76e4cae2-d49c-44ec-8637-ab46ad4497c1.png)

**Comment by dracos** [comment]
App no longer in use
