### ISSUE TITLE
Report flow asking for category without any selection options.

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet-mobile#303]
From user support inbox:
> asking me to choose a category but there are no drop downs or options to choose anything

iPhone 8 plus iOS 16.3.

![choose category bug report](https://user-images.githubusercontent.com/9289297/217831809-7f2bddbb-aa69-4d30-9b8b-2748231b98ae.png)

**Comment by dracos** [comment]
App no longer in use
