### ISSUE TITLE
Unable to login with web created account.

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet-mobile#304]
From user support inbox:
> I've created an account on your website. I've then downloaded the app but I can't log with my username and password. I've triple checked it's the correct one but won't log me on.

Android 10. App version 2.6

![login bug report](https://user-images.githubusercontent.com/9289297/217864026-02f8f339-0e4f-4cff-b3d7-44b5bf464034.jpg)

**Comment by dracos** [comment]
App no longer in use
